### PR TITLE
Firebase format and context save

### PR DESCRIPTION
**Pull request by cflorion**
This pull request contains 2 commits:
1. Added method sync_toManyRelationshipUsingIDsInDictionary
   I am using Firebase as a database, and the best practice to handle relationships in Firebase is not to use an array of ids (i.e. ["aaa", "bbb"]) but to use a dictionary with the id as a key and true as a value (i.e. {"aaa": true, "bbb": true}. So I added a method to handle this case. Please tell me if this is the place to do that, I am not sure.
2. Added shouldSave parameter in the changes function
   My use case: I have 2 objects: Team and Player. I receive from my backend an array of Team and an array of players. Therefore I have 2 separate arrays that I want to import. I call the changes(...) function for the Team and I have a log message from Sync that says that it could not find the players that the team is supposed to point to. That's normal because the Player import is the batch coming just after. At the end of the Team import, the Core Data save does the data validation and raise an exception since in my model a Team must have at least one player.

In my opinion the Core Data save should not happen after each entity import. It should happen when you have imported all your entities. Indeed, a Team points to Players and a Player points to a Team. So if you import the Team first it will not find the players, but afterwards when you import the Players, you will find the Team and Core Data will fill the inverse relationship for you.

So in my commit I added a shouldSave parameter in the changes(...) function. It set to false, the save doesn't happen, and I do it myself in the completion block. Like so:

```
 self.dataStack.performInNewBackgroundContext { backgroundContext in
            let group = DispatchGroup.init()
            for anEntityName in self.entityNames {
                group.enter()
                let objects = objectsForEntity[entityName]

                backgroundContext.perform({
                    Sync.changes(objects, inEntityNamed: entityName, predicate: nil, parent: nil, inContext: backgroundContext, dataStack: self.dataStack, completion: { (error) in
                        group.leave()
                    })
                })
            }

            group.notify(queue: DispatchQueue.main) {
                backgroundContext.perform({
                    backgroundContext.saveToPersistentStore(completion: { (success, error) in
                        DispatchQueue.main.async {
                            completion?(success, error)
                        }
                    })
                })

            }
        }
```

A save is a batch of changes. So to summarize, in my opinion the granularity should not just be an entity. This may be only true in my use case, what do you think ?

### CODE REVIEW

**Comment by 3lvis** [comment]
Hi @cflorion,

Thanks for sharing your ideas :) 

1.- Do you know why Firebase does this? First time I see this in a backend.

2.- Is there any reason why you won't save all your players first, then save the teams, so the players are linked correctly to the team they belong?

**Comment by cflorion** [comment]
1. This is an assumption but: Firebase is just a key-value store. Strings as keys, and dictionary as values. So it cannot store arrays.
2. The reason is true in my use case: I import the whole object graph at once. What I like about Core Data is its validations of data: property optional or not, relationship optional or not, default values etc. In my case a Player MUST have a team, so in the Core Data model I put this attribute as non-optional. But if I import players first and them teams, of course Core Data will raise an exception indicating that the data validation is wrong if I save (when the validation occurs) after each entity import.
But what I'm saying is only true if you import everything at once. If you import objects as they arrive, it's not possible to do the validation since it will always raise an exception. In that case I should put optional for the relationship, even though I don't like that a player without a team is technically possible...

It's hard to explain my thoughts, but I hope you get what I mean a bit :) 

I don't so if this is a common case, that's why I put a "save" parameter to the method so it gives you the choice when implementing. In my case I use both options.

**Comment by 3lvis** [comment]
Hi @cflorion,

Sorry for not taking care of this PR as it should. :( 

Would be nice to add Firebase support in an extension. Instead of on the main Sync.swift mainly to keep it agnostic.

Regarding the additional flag, I'm not sure if it would be a good idea since I can see people using it and reporting bugs because things didn't got saved.

**Comment by 3lvis** [comment]
Closing since Firebase support is not considered as a main feature.

**Pull request closed without merging**
