### PR TITLE
Feature: Extend operation options

### PR DESCRIPTION
**Pull request by 3lvis**
Adds the ability to tell Sync to insert, remove or updates relationships.

- [x] One-to-many
- [x] Many-to-many
- [ ] One-to-one

### CODE REVIEW

**Comment by aamir-nazir** [comment]
@3lvis when we are planing to merge this feature in master?

**Comment by 3lvis** [comment]
@aamir-nazir Need to get the other operations in place, I'm happy to receive some help :)

**Comment by aamir-nazir** [comment]
@3lvis yes sure, I am up for to do some of the tasks.

**Comment by 3lvis** [comment]
@aamir-nazir Added you as a collaborator https://github.com/3lvis/Sync/invitations

I think a good place to start would be to understand the unit tests added in this PR and add more unit tests for the remaining cases.

Adds the ability to tell Sync to insert, remove or updates relationships.

- [ ] Many-to-many
- [ ] One-to-one

**Comment by aamir-nazir** [comment]
@3lvis do we seeking more Test Cases? I can be able to implement some of them on weekend.

**Comment by 3lvis** [comment]
@aamir-nazir For Many-to-many and One-to-one I've added a JSON and a Core Data model but the unit tests were just copied from One-to-many, so we still need tests for many-to-many and one-to-one. Thanks for your help!

**Comment by batjo** [comment]
@3lvis I don't think this needs to be implemented for one-to-one right? I can see the use case for one-to-many and many-to-many.

**Comment by batjo** [comment]
I just fixed the tests for the many-to-many relationships. Code was already working, it was just that the tests where wrong. Still I don't see the use case for a one-to-one relationship. The use case that has been described by others (where the server only sends the last x messages instead of all messages) makes sense to me. But for a one-to-one relationship it doesn't make sense since the json will always contain the object.

**Comment by 3lvis** [comment]
I agree @batjo! Is better to get it out and get feedback as well. Thanks for your help!

**Pull request merged**
