### PR TITLE
Add compatibleSync method for DataStack.

### PR DESCRIPTION
**Pull request by lm2343635**
I found sync method of DataStack cannot use operations too, so I made this pull request.

### CODE REVIEW

**Comment by 3lvis** [comment]
Hi @lm2343635!

I'm trying to keep the codebase as simple as possible, is it possible that you include these helpers just in your project? We can always revisit if someone else needs this.

Thanks!

**Comment by lm2343635** [comment]
It's OK for me to use the class method Sync.changes.
I want to know the differences between the class method and the instance method dataStack.sync

**Comment by 3lvis** [comment]
Instance method is just a convenience method.

**Comment by 3lvis** [comment]
Closing since it can be added as a local helper method.

**Pull request closed without merging**
