### PR TITLE
Boolean ignored issue 449

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by 3lvis** [comment]
After modifying the query seems to be working fine, I didn't do any logic changes in Sync.

**Comment by 3lvis** [comment]
Hi @max-pfeiffer,

Looking forward to getting your feedback on this.

**Comment by max-pfeiffer** [comment]
@3lvis : I double checked the issue: it was an error in the JSON which was delivered by the server. "true"/"false" was delivered instead of true/false as JSON Value. Google Gson eats it, which we use for Android. But the behaviour of your library is absolutely correct.

So error was on my side, sorry about that.

**Comment by 3lvis** [comment]
Thanks for the additional info, @max-pfeiffer!

**Pull request closed without merging**
