### PR TITLE
Support for Omit Null values

### PR DESCRIPTION
**Pull request by markst**
#503

### CODE REVIEW

**Comment by markst** [comment]
Is there any reason why `ExportOptions` can't be defined as a `enum`?
```swift
enum ExportOptions {
    case inflectionType(InflectionType)
    case relationshipType(RelationshipType)
    case dateFormatter(DateFormatter)
    case omitNullValues(Bool)
}
```

**Comment by 3lvis** [comment]
Hi @markst,

Great initiative! Any chance you could add a unit test to make sure these changes don't get reverted by accident?

Thanks again :)

**Comment by 3lvis** [comment]
Regarding your question on making it an enum, it's beacause it should be possible to combine multiple options, like setting inflectionType, relationshipType, dateFormatting and so on. If it's an enum you can only do one.

**Comment by 3lvis** [comment]
Added the help-wanted flag, the feature works well just needs the unit tests.

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.

**Pull request closed without merging**
